target-version = "py310"

[lint]
select = [
    "UP",      # pyupgrade
    "C4",      # flake8-comprehensions
    "E713",    # use 'key not in list'
    "NPY201",  # NumPy 2 compatibility
    "PIE",     # flake8-pie
    "PGH003",  # forbid blanket 'type: ignore' comments
    "PLR0402", # useless import alias
    "SIM101",  # merge 'isinstance' calls
    "SIM109",  # use a tuple for multiple comparisons
    "SIM110",  # convert loop to 'any'
    "SIM118",  # use 'key in dict'
    "SIM2",    # simplify boolean comparisons
]

[format]
docstring-code-format = true
