target-version = "py310"

[lint]
select = [
  "B",       # flake8-bugbear
  "C4",      # flake8-comprehensions
  "E",
  "EM",      # flake8-errmsg
  "PGH",     # pygrep-hooks
  "PIE",     # flake8-pie
  "PL",      # pylint
  # "PTH",     # flake8-use-pathlib
  # "RET",     # flake8-return
  "RUF",     # Ruff-specific
  "SIM",     # flake8-simplify
  "UP",      # pyupgrade
  "SIM2",    # simplify boolean comparisons
  "YTT",     # flake8-2020
  "EXE",     # flake8-executable
  "NPY",     # NumPy specific rules
  "PD",      # pandas-vet
  "FURB",    # refurb
  "PYI"      # flake8-pyi
]
ignore = [
  "B006",
  "B007",
  "B018",
  "E402",     # Module level import not at top of file
  "E501",     # Line too long
  "E741",     # Ambiguous variable name
  "E721",     # Do not compare types, use `isinstance()`
  "E731",     # Do not assign a `lambda` expression, use a `def`
  "EM101",
  "EM102",
  "SIM115",
  "PLR",
  "PLW0127",
  "RUF015",
  "RUF005",
  "PLW2901",
  "NPY002",
  "PD002",
  "PLR09",    # Too many <...>
  "PLR2004",  # Magic value used in comparison
  "ISC001"    # Conflicts with formatter
]

[format]
docstring-code-format = true
